### ISSUE TITLE
Try to upstream delay-password?

### ISSUE THREAD

**Issue by mauro3** [gdamjan/swaylock#1]
Seems like a useful feature to me.

**Comment by gdamjan** [comment]
I did try, they didn't want it

**Comment by mauro3** [comment]
Oh, ok.  I didn't see the PR.

**Comment by gdamjan** [comment]
I don't think I did open a PR, but I talked to people on the #sway irc, and they weren't interested.

Maybe you could try your luck convincing them - I'm not using sway any more*, and I'm not interested in engaging with that community.

* except when testing different wayland implementations, which is rare these days.

**Comment by mauro3** [comment]
Well, having read a few threads over there, I'm not convinced either.  I might give https://github.com/mortie/swaylock-effects a spin.
